# This workflow will install dependencies, build application, run tests and upload their coverage to codecov, check if code is properly linted and formatted

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Use Node.js 16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: '16'
          cache: 'npm'

      - name: Disable prepare script
        run: npm set-script prepare ""

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
        with:
          files: coverage/lcov.info

      - name: Lint code
        run: npm run lint:ci

      - name: Check code style
        run: npm run format:ci
